[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
solc_version = "0.8.29"

[profile.diamond]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
solc_version = "0.8.29"
# Focus on diamond contracts only
include = [
    "src/diamond/**/*.sol",
    "src/shared/**/*.sol"
]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
lisk_sepolia = "${LISK_SEPOLIA_RPC_URL}"

[etherscan]
lisk_sepolia = { key = "", url = "https://sepolia-blockscout.lisk.com/api" }